cd C:/Users/sarto/Documents/Travail/M1/M&T/GAYA_SARTORIUS_cheap-SERUM/firmware1
PATH=%PATH%\\\;C:/Users/sarto/Documents/Pd/externals/Fraise/bin/utils
PATH=%PATH%\\\;C:/Users/sarto/Documents/Pd/externals/Fraise/bin/win32
del C:/Users/sarto/Documents/Travail/M1/M&T/GAYA_SARTORIUS_cheap-SERUM/firmware1/firmware1.map
del C:/Users/sarto/Documents/Travail/M1/M&T/GAYA_SARTORIUS_cheap-SERUM/firmware1/make.err
if not exist "firmware1-objs/fruit" md "firmware1-objs/fruit"
C:/Users/sarto/Documents/Pd/externals/Fraise/bin/win32/sdcc --use-stdout -I"C:/Users/sarto/Documents/Pd/externals/Fraise/fruit" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/eeparams" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/core" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/fraisedevice" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/analog" -DUD_SETUP -DUD_LOOP -DUD_RCVC -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"C:/Users/sarto/Documents/Pd/externals/Fraise/boards/Versa2" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/non-free/include/pic16" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/include/pic16" -c "C:/Users/sarto/Documents/Pd/externals/Fraise/fruit/fruit.c" -o "firmware1-objs/fruit/fruit.o" >> make.err
if not exist "firmware1-objs/eeparams" md "firmware1-objs/eeparams"
C:/Users/sarto/Documents/Pd/externals/Fraise/bin/win32/sdcc --use-stdout -I"C:/Users/sarto/Documents/Pd/externals/Fraise/fruit" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/eeparams" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/core" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/fraisedevice" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/analog" -DUD_SETUP -DUD_LOOP -DUD_RCVC -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"C:/Users/sarto/Documents/Pd/externals/Fraise/boards/Versa2" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/non-free/include/pic16" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/include/pic16" -c "C:/Users/sarto/Documents/Pd/externals/Fraise/eeparams/eeparams.c" -o "firmware1-objs/eeparams/eeparams.o" >> make.err
if not exist "firmware1-objs/core" md "firmware1-objs/core"
C:/Users/sarto/Documents/Pd/externals/Fraise/bin/win32/sdcc --use-stdout -I"C:/Users/sarto/Documents/Pd/externals/Fraise/fruit" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/eeparams" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/core" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/fraisedevice" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/analog" -DUD_SETUP -DUD_LOOP -DUD_RCVC -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"C:/Users/sarto/Documents/Pd/externals/Fraise/boards/Versa2" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/non-free/include/pic16" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/include/pic16" -c "C:/Users/sarto/Documents/Pd/externals/Fraise/core/core.c" -o "firmware1-objs/core/core.o" >> make.err
if not exist "firmware1-objs/fraisedevice" md "firmware1-objs/fraisedevice"
C:/Users/sarto/Documents/Pd/externals/Fraise/bin/win32/sdcc --use-stdout -I"C:/Users/sarto/Documents/Pd/externals/Fraise/fruit" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/eeparams" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/core" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/fraisedevice" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/analog" -DUD_SETUP -DUD_LOOP -DUD_RCVC -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"C:/Users/sarto/Documents/Pd/externals/Fraise/boards/Versa2" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/non-free/include/pic16" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/include/pic16" -c "C:/Users/sarto/Documents/Pd/externals/Fraise/fraisedevice/fraisedevice.c" -o "firmware1-objs/fraisedevice/fraisedevice.o" >> make.err
if not exist "firmware1-objs/analog" md "firmware1-objs/analog"
C:/Users/sarto/Documents/Pd/externals/Fraise/bin/win32/sdcc --use-stdout -I"C:/Users/sarto/Documents/Pd/externals/Fraise/fruit" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/eeparams" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/core" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/fraisedevice" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/analog" -DUD_SETUP -DUD_LOOP -DUD_RCVC -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"C:/Users/sarto/Documents/Pd/externals/Fraise/boards/Versa2" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/non-free/include/pic16" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/include/pic16" -c "C:/Users/sarto/Documents/Pd/externals/Fraise/analog/analog.c" -o "firmware1-objs/analog/analog.o" >> make.err
C:/Users/sarto/Documents/Pd/externals/Fraise/bin/win32/sdcc --use-stdout -DUD_SETUP -DUD_LOOP -DUD_RCVC -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"C:/Users/sarto/Documents/Pd/externals/Fraise/boards/Versa2" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/non-free/include/pic16" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/include/pic16" -c "C:/Users/sarto/Documents/Pd/externals/Fraise/core/crt0iz-rloc.c" -o "firmware1-objs/crt.o" >> make.err
C:/Users/sarto/Documents/Pd/externals/Fraise/bin/win32/sdcc --use-stdout -DUD_SETUP -DUD_LOOP -DUD_RCVC -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"C:/Users/sarto/Documents/Pd/externals/Fraise/boards/Versa2" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/non-free/include/pic16" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/include/pic16" -c "C:/Users/sarto/Documents/Pd/externals/Fraise/boards/Versa2/boardconfig.c" -o "firmware1-objs/boardconfig.o" >> make.err
C:/Users/sarto/Documents/Pd/externals/Fraise/bin/win32/sdcc --use-stdout -DUD_SETUP -DUD_LOOP -DUD_RCVC -I. -mpic16 --vc --denable-peeps --optimize-cmp --optimize-df --obanksel=2 --opt-code-speed --fomit-frame-pointer --use-non-free --std-sdcc99 -p18f26k22 -I"C:/Users/sarto/Documents/Pd/externals/Fraise/boards/Versa2" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/non-free/include/pic16" -I"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/include/pic16" --use-crt="firmware1-objs/crt.o" -L"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/lib/pic16" -L"C:/Users/sarto/Documents/Pd/externals/Fraise/bin/share/non-free/lib/pic16" -Wl"-O 1 -m -w -s C:/Users/sarto/Documents/Pd/externals/Fraise/boards/Versa2/board.lkr" -o "firmware1.hex" libsdcc.lib libc18f.lib libdev18f26k22.lib libm18f.lib "firmware1-objs/boardconfig.o" "firmware1-objs/firmware1.o" "firmware1-objs/fruit/fruit.o" "firmware1-objs/eeparams/eeparams.o" "firmware1-objs/core/core.o" "firmware1-objs/fraisedevice/fraisedevice.o" "firmware1-objs/analog/analog.o" >> make.err
echo make_done | to_pd 41424
